# Generated by Django 4.2 on 2023-04-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
